# Generated by Django 4.2.27 on 2026-01-23 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('propietario', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Nivel 1', 'Obediencia básica'), ('Nivel 2', 'Control Avanzado'), ('Nivel 3', 'Entrenamiento de deportivo'), ('SO', 'Sociabilización')], max_length=10)),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('observaciones', models.TextField(blank=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='perros.perro')),
            ],
        ),
    ]
