# Generated by Django 4.2.27 on 2026-01-23 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to=settings.AUTH_USER_MODEL),
        ),
    ]
