# Generated by Django 4.2.27 on 2026-02-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_alter_perro_propietario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrenamiento',
        ),
    ]
