# Generated by Django 4.2.27 on 2026-02-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perros', '0003_delete_entrenamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Nivel 1', 'Obediencia básica'), ('Nivel 2', 'Control Avanzado'), ('Nivel 3', 'Entrenamiento de deportivo'), ('SO', 'Sociabilización')], max_length=10)),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('observaciones', models.TextField(blank=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='perros.perro')),
            ],
        ),
    ]
